# Generated by Django 4.2.21 on 2025-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproduct',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130'), ('Standard', 'Standard')], default='M', max_length=255),
        ),
    ]
