# Generated by Django 4.2.23 on 2025-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_color'),
        ('wishlist', '0002_remove_wishlist_products_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='app.product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
