# Generated by Django 4.2.21 on 2025-08-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
        ('wishlist', '0004_wishlistproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistproduct',
            unique_together={('wishlist', 'product', 'size')},
        ),
    ]
