# Generated by Django 4.2.23 on 2025-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_remove_wishlist_products_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
