# Generated by Django 4.2.21 on 2025-08-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
        ('wishlist', '0005_alter_wishlistproduct_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'product', 'size')},
            },
        ),
        migrations.DeleteModel(
            name='WishlistProduct',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, through='wishlist.WishlistItem', to='app.product'),
        ),
    ]
