# Generated by Django 4.2.23 on 2025-08-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('wishlist', '0005_remove_wishlistitem_quantity_alter_wishlistitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='app.product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
