# Generated by Django 4.2.23 on 2025-09-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(choices=[('RED', 'Црвена'), ('BLUE', 'Плава'), ('GREEN', 'Зелена'), ('BLACK', 'Црна'), ('WHITE', 'Бела'), ('YELLOW', 'Жолта'), ('ORANGE', 'Портокалова'), ('PURPLE', 'Виолетова'), ('PINK', 'Розева'), ('BROWN', 'Кафена'), ('GRAY', 'Сива'), ('SILVER', 'Сребрена'), ('GOLD', 'Златна'), ('BEIGE', 'Беж'), ('CYAN', 'Цијан'), ('MAGENTA', 'Магента'), ('NAVY', 'Морнарско сина'), ('TEAL', 'Тиркизна'), ('OLIVE', 'Маслинеста'), ('MAROON', 'Бордо')], max_length=20)),
                ('category', models.CharField(choices=[('BRAS', 'Градници'), ('PANTIES', 'Килоти'), ('LINGERIE', 'Приватна'), ('PAJAMAS', 'Пижами'), ('TSHIRT', 'Маици'), ('BODICES', 'Мидери'), ('LEGGINGS', 'Хеланки'), ('NIGHTCLOTHES', 'Ноќници'), ('KITS', 'Комплети'), ('BABY_DOLL', 'Бебидол'), ('ACCESSORIES', 'Додатоци')], default='BRAS', max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('BRAS_PUSH_UP', 'Градници - Push-up'), ('BRAS_SPORT', 'Градници - Спортски'), ('BRAS_LACE', 'Градници - Чипкани'), ('BRAS_UNDERWIRE', 'Градници - Без жица'), ('BRAS_STICK', 'Градници - Лепенки'), ('PANTIES_TANGA', 'Килоти - Танга'), ('PANTIES_HALF_TANGA', 'Килоти - Полутанга'), ('PANTIES_HIGH_WAIST', 'Килоти - Високи'), ('BOXER_PANTIES', 'Килоти - Боксерки'), ('PAJAMAS_SHORT', 'Пижами - Кратки'), ('PAJAMAS_LONG', 'Пижами - Долги'), ('PAJAMAS_SATEN', 'Пижами - Сатенски'), ('PAJAMAS_PLIS', 'Пижами - Плишани'), ('PAJAMAS_COTTON', 'Пижами - Памучни'), ('PAJAMAS_MAN', 'Пижами - Машки')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130'), ('Standard', 'Standard')], max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
        ),
    ]
