# Generated by Django 5.2.1 on 2025-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bras', 'Bras'), ('panties', 'Panties'), ('lingerie', 'Lingerie'), ('knitwear', 'Knitwear'), ('pajamas', 'Pajamas')], default='bras', max_length=50),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
    ]
