# Generated by Django 4.2.23 on 2025-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bras', 'Bras'), ('panties', 'Panties'), ('lingerie', 'Lingerie'), ('pajamas', 'Pajamas')], default='bras', max_length=50),
        ),
    ]
