# Generated by Django 5.2.1 on 2025-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_alter_productquantity_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bras', 'Bras'), ('panties', 'Panties'), ('lingerie', 'Lingerie'), ('pajamas', 'Pajamas')], default='bras', max_length=50),
        ),
    ]
