# Generated by Django 5.2.1 on 2025-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
        ('app', '0003_alter_product_category'),
    ]

    operations = [
    ]
