# Generated by Django 5.2.5 on 2025-08-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
        ('app', '0003_alter_product_category'),
    ]

    operations = [
    ]
