# Generated by Django 4.2.23 on 2025-08-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250819_1543'),
        ('app', '0006_delete_profile'),
    ]

    operations = [
    ]
