# Generated by Django 4.2.23 on 2025-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0004_merge_20250819_1543_0006_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('RED', 'Црвена'), ('BLUE', 'Плава'), ('GREEN', 'Зелена'), ('BLACK', 'Црна'), ('WHITE', 'Бела')], max_length=20),
        ),
    ]
