# Generated by Django 4.2.23 on 2025-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Градници', 'Градници'), ('Килоти', 'Килоти'), ('Приватна', 'Приватна'), ('Пижами', 'Пижами')], default='Градници', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('RED', 'Црвена'), ('BLUE', 'Плава'), ('GREEN', 'Зелена'), ('BLACK', 'Црна'), ('WHITE', 'Бела'), ('YELLOW', 'Жолта'), ('ORANGE', 'Портокалова'), ('PURPLE', 'Виолетова'), ('PINK', 'Розева'), ('BROWN', 'Кафена'), ('GRAY', 'Сива'), ('SILVER', 'Сребрена'), ('GOLD', 'Златна'), ('BEIGE', 'Беж'), ('CYAN', 'Цијан'), ('MAGENTA', 'Магента'), ('NAVY', 'Морнарско сина'), ('TEAL', 'Тиркизна'), ('OLIVE', 'Маслинеста'), ('MAROON', 'Бордо')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130')], max_length=5),
        ),
    ]
