# Generated by Django 4.2.21 on 2025-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_category_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BRAS', 'Градници'), ('PANTIES', 'Килоти'), ('LINGERIE', 'Приватна'), ('PAJAMAS', 'Пижами'), ('TSHIRT', 'Маици'), ('BODICES', 'Мидери'), ('LEGGINGS', 'Хеланки'), ('NIGHTCLOTHES', 'Ноќници'), ('KITS', 'Комплети'), ('BABY_DOLL', 'Бебидол'), ('ACCESSORIES', 'Додатоци'), ('PANTIES_TANGA', 'Килоти - Танга'), ('PANTIES_HALF_TANGA', 'Килоти - Полутанга'), ('PANTIES_HIGH_WAIST', 'Килоти - Високи'), ('BOXER_PANTIES', 'Килоти - Боксерки'), ('BRAS_PUSH_UP', 'Градници - Push-up'), ('BRAS_SPORT', 'Градници - Спортски'), ('BRAS_LACE', 'Градници - Чипкани'), ('BRAS_UNDERWIRE', 'Градници - Без жица'), ('PAJAMAS_SHORT', 'Пижами - Кратки'), ('PAJAMAS_LONG', 'Пижами - Долги')], default='BRAS', max_length=50),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130'), ('Standard', 'Standard')], max_length=255),
        ),
    ]
