# Generated by Django 4.2.21 on 2025-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_category_alter_productquantity_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BRAS', 'Градници'), ('PANTIES', 'Килоти'), ('LINGERIE', 'Приватна'), ('PAJAMAS', 'Пижами'), ('TSHIRT', 'Маици'), ('BODICES', 'Мидери'), ('LEGGINGS', 'Хеланки'), ('NIGHTCLOTHES', 'Ноќници'), ('KITS', 'Комплети'), ('BABY_DOLL', 'Бебидол'), ('ACCESSORIES', 'Додатоци'), ('PANTIES_TANGA', 'Килоти - Танга'), ('PANTIES_HALF_TANGA', 'Килоти - Полутанга'), ('PANTIES_HIGH_WAIST', 'Килоти - Високи'), ('BOXER_PANTIES', 'Килоти - Боксерки'), ('BRAS_PUSH_UP', 'Градници - Push-up'), ('BRAS_SPORT', 'Градници - Спортски'), ('BRAS_LACE', 'Градници - Чипкани'), ('BRAS_UNDERWIRE', 'Градници - Без жица'), ('BRAS_STICK', 'Градници - Лепенки'), ('PAJAMAS_SHORT', 'Пижами - Кратки'), ('PAJAMAS_LONG', 'Пижами - Долги'), ('PAJAMAS_SATEN', 'Пижами - Сатенски'), ('PAJAMAS_PLIS', 'Пижами - Плишани'), ('PAJAMAS_COTTON', 'Пижами - Памучни'), ('PAJAMAS_MAN', 'Пижами - Машки Пижами')], default='BRAS', max_length=50),
        ),
    ]
