# Generated by Django 4.2.23 on 2025-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_comment_order_phone_number_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
